from .node import LLMAPIChatNode


NODE_CLASS_MAPPINGS = {
    "LLM_API_CHAT_NODE": LLMAPIChatNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "LLM_API_CHAT_NODE": "LLM API Chat",
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
